FROM python:3.9-slim
WORKDIR /app
COPY ./requirements_dash.txt /app/
RUN pip install --no-cache-dir -r requirements_dash.txt
COPY ./src/dashboard.py /app/
EXPOSE 8501
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]